export const SET_CURRENT_EMPLOYEE_REQUEST = "SET_CURRENT_EMPLOYEE_REQUEST";
export const SET_CURRENT_EMPLOYEE_SUCESS = "SET_CURRENT_EMPLOYEE_SUCESS";
export const SET_CURRENT_EMPLOYEE_FAILURE = "SET_CURRENT_EMPLOYEE_FAILURE";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
